# Generated by Django 4.2.20 on 2025-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_quote_created_at_quote_created_by_quote_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
