# Generated by Django 4.2.20 on 2025-04-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_quote_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='updated_at',
        ),
    ]
