# Generated by Django 4.2.20 on 2025-04-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_quote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
    ]
