# Generated by Django 4.2.20 on 2025-04-30 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scraper', '0008_quote_created_at_quote_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
