# Generated by Django 4.2.20 on 2025-04-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_quote_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='updated_by',
        ),
    ]
